### ISSUE TITLE
What are the percent ratings for all the trims and where do they all spawn? ( If they even spawn at all)

### ISSUE THREAD

**Issue by JasonBean-99** [Hipposgrumm/armor-trims#12]
Sorry, I couldn't find a question area and saw there wasn't a discord to ask. But as the title says are you able to find the trims in structures? I looked for a bit but didn't see any and if so what are the % ratings and where are they located? Also, will this mod work if Im adding it to a server that has 400ish mods with all different sorts of armours and gear? or will this cause FPS issues?

And I assume if I add it to my already established server I just have to find new chunks?

Thank you for taking the time to read my questions 👍 :)

Ps you should make a discord server  so that it's easier to keep track of updates and progress

**Comment by Hipposgrumm** [comment]
The armor trims should be generating in structures. The spawn locations will not be the same as the ones from 1.20 (due to differences in IDs and such. The spawn rates should be the same as the regular armor trims we're at some point (unless they haven't changed since I last checked the wiki), rounded to the nearest whole number for simplicity.

There is currently #5 which I have no idea of the cause, so it is probably best to not use this in a big modpack it would be a great way to kill your friends' GPU.

In an already generated world, they will spawn in chests that haven't been opened and their loot tables not generated yet (which is why you can only open structure chests that have already been opened in spectator mode).

As for a Discord server, I'll have to think about it.

**Comment by Hipposgrumm** [comment]
I forgot to mention that I screwed something up in 1.2 (#11) where it will only load the trim textures on already loaded items when creating them (and this mod comes before a lot of others alphabetically). I will release a patch soon but I will tell you to wait until it is released.

**Comment by JasonBean-99** [comment]
Sounds good thanks for the response 👍
